version: "3.8"

services:
  mongo:
    image: mongo:7
    container_name: mongo-pems
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: traffic-backend
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URL: mongodb://mongo:27017/trafficDB
    depends_on:
      - mongo

volumes:
  mongo_data: